#!/usr/bin/env node
/**
 * Replace release placeholders in the static landing page generated by Vite.
 *
 * The release workflow knows the XPI URL immediately after signing. The pages
 * refresh workflow does not, so it reads public-pages/updates.json and derives
 * the latest version/link from there.
 */
import { readFileSync, writeFileSync } from 'node:fs';
import { basename, resolve } from 'node:path';

const outDir = process.env.PUBLIC_PAGES_DIR ?? 'public-pages';
const htmlPath = resolve(outDir, 'index.html');
const updatesPath = resolve(outDir, 'updates.json');

const addonId = process.env.ADDON_ID ?? 'contabox@galih.dev';
const repoUrl = process.env.REPO_URL ?? 'https://github.com/pripanggalih/contabox';
const updatesUrl =
  process.env.UPDATES_URL ?? 'https://pripanggalih.github.io/contabox/updates.json';

const latestFromUpdates = readLatest(updatesPath, addonId);
const version = process.env.VERSION ?? latestFromUpdates.version ?? '0.1.0';
const xpiUrl = process.env.XPI_URL ?? latestFromUpdates.updateLink ?? repoUrl;
const xpiName = process.env.XPI_NAME ?? basename(xpiUrl);

let html = readFileSync(htmlPath, 'utf8');
const replacements = {
  __VERSION__: version,
  __XPI_URL__: xpiUrl,
  __XPI_NAME__: xpiName,
  __REPO_URL__: repoUrl,
  __UPDATES_URL__: updatesUrl,
  __BUILD_DATE__: new Date().toISOString(),
};

for (const [key, value] of Object.entries(replacements)) {
  html = html.split(key).join(escapeHtmlAttr(value));
}

writeFileSync(htmlPath, html);

function readLatest(path, id) {
  try {
    const json = JSON.parse(readFileSync(path, 'utf8'));
    const updates = json.addons?.[id]?.updates ?? [];
    const sorted = [...updates].sort((a, b) =>
      String(a.version).localeCompare(String(b.version), undefined, { numeric: true }),
    );
    const latest = sorted.at(-1);
    return {
      version: latest?.version,
      updateLink: latest?.update_link,
    };
  } catch {
    return {};
  }
}

function escapeHtmlAttr(value) {
  return String(value)
    .replace(/&/g, '&amp;')
    .replace(/"/g, '&quot;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;');
}
